# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Simmons Farm At Limeledge
description: >- # this means to ignore newlines until "baseurl:"
  At Simmons Farm, we take inspiration from the balance of natural system to help landowners 
  design customized, holistic plans for maximizing the potential of their landscapes and gardens.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings

plugins:
  - jekyll-feed
  - pagemaster

collections:
  abies:
    output: true
    family-name: Pinaceae
    genus-name: Abies
    source: abies-all.json
    id_key: species-name
    layout: species
    permalink: /trees/pinaceae/:collection/:name
  cathaya:
    output: true
    family-name: Pinaceae
    genus-name: Cathaya
    permalink: /trees/pinaceae/:collection/:name
  cedrus:
    output: true
    family-name: Pinaceae
    genus-name: cedrus
    id_key: species-name
    layout: species
    source: cedrus.json
    permalink: /trees/pinaceae/:collection/:name
  keteleeria:
    output: true
    family-name: Pinaceae
    genus-name: keteleeria
    permalink: /trees/pinaceae/:collection/:name
  larix:
    output: true
    family-name: Pinaceae
    genus-name: larix
    id_key: species-name
    layout: species
    source: larix.json
    permalink: /trees/pinaceae/:collection/:name
  nothotsuga:
    output: true
    family-name: Pinaceae
    genus-name: nothotsuga
    permalink: /trees/pinaceae/:collection/:name
  picea:
    output: true
    family-name: Pinaceae
    genus-name: picea
    id_key: species-name
    layout: species
    source: picea.json
    permalink: /trees/pinaceae/:collection/:name
  pinus:
    output: true
    family-name: Pinaceae
    genus-name: pinus
    id_key: species-name
    layout: species
    source: pinus.json
    permalink: /trees/pinaceae/:collection/:name
  pseudolarix:
    output: true
    family-name: Pinaceae
    genus-name: pseudolarix
    id_key: species-name
    layout: species
    source: pseudolarix.json
    permalink: /trees/pinaceae/:collection/:name
  pseudotsuga:
    output: true
    family-name: Pinaceae
    genus-name: pseudotsuga
    id_key: species-name
    layout: species
    source: pseudotsuga.json
    permalink: /trees/pinaceae/:collection/:name
  tsuga:
    output: true
    family-name: Pinaceae
    genus-name: tsuga
    id_key: species-name
    layout: species
    source: tsuga.json
    permalink: /trees/pinaceae/:collection/:name
